package it.polimi.ingsw.galaxytrucker.network.socket.message;

public enum GameUpdateType {
    ERROR,
    WAITING_FOR_PLAYERS,
    NEW_PLAYER,
    START_ASSEMBLING,
    PICKED_COMPONENT,
    SHOWN_COMPONENT,
    RESERVED_COMPONENT,
    ROTATE_PICKED_COMPONENT,
    ASSEMBLED_COMPONENT,
    PICKED_DECK,
    RELEASED_DECK,
    FINISH_ASSEMBLING,
    SHIP_CONTROL,
    DESTROYED_COMPONENT,
    CARD_PICKING,
    NEXT_TURN,
    PLAYER_QUIT,
    CARD_SOLVING,
    CREW_CHANGE,
    ALIEN_CHANGE,
    BATTERY_CHANGE,
    CREDITS_CHANGE,
    POSITION_CHANGE,
    END_GAME
}
